/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
        "colors": {
            "on-secondary-fixed": "var(--on-surface-variant)",
            "primary": "var(--primary)",
            "surface-tint": "var(--surface-container-highest)",
            "on-secondary": "var(--on-surface)",
            "primary-fixed": "#dae2fd",
            "surface-variant": "#e0e3e5",
            "on-tertiary-fixed-variant": "#653e00",
            "success": "#10B981",
            "success-emerald": "#10B981",
            "primary-container": "var(--primary-container)",
            "surface-container-lowest": "var(--surface-container-lowest)",
            "on-background": "var(--on-surface)",
            "accent-blue": "var(--accent-blue)",
            "inverse-on-surface": "#eff1f3",
            "on-primary-container": "#7c839b",
            "on-tertiary": "#ffffff",
            "tertiary": "#000000",
            "secondary-fixed-dim": "#b4c5ff",
            "on-secondary-fixed-variant": "#003ea8",
            "on-surface": "var(--on-surface)",
            "surface-container-highest": "var(--surface-container-highest)",
            "on-primary": "var(--bg-base)",
            "outline": "var(--outline-variant)",
            "background": "var(--bg-base)",
            "dark-navy": "var(--dark-navy)",
            "surface-glass": "var(--glass-bg)",
            "surface-container-high": "var(--surface-container-highest)",
            "tertiary-container": "#2a1700",
            "error-container": "#ffdad6",
            "outline-variant": "var(--outline-variant)",
            "on-primary-fixed": "var(--primary-container)",
            "on-primary-fixed-variant": "#3f465c",
            "surface-container": "var(--surface-container-highest)",
            "error": "#EF4444",
            "surface-dim": "var(--border-slate)",
            "secondary": "#0051d5",
            "on-tertiary-container": "#b87500",
            "inverse-surface": "#2d3133",
            "tertiary-fixed-dim": "#ffb95f",
            "on-tertiary-fixed": "#2a1700",
            "on-error-container": "#93000a",
            "surface-bright": "#f7f9fb",
            "surface-container-low": "#f2f4f6",
            "secondary-fixed": "#dbe1ff",
            "pale-blue": "#EFF6FF",
            "slate-muted": "#64748B",
            "on-error": "#ffffff",
            "tertiary-fixed": "#ffddb8",
            "on-surface-variant": "var(--on-surface-variant)",
            "surface": "var(--bg-base)",
            "secondary-container": "var(--accent-blue)",
            "border-light": "var(--border-slate)",
            "border-slate": "var(--border-slate)",
            "inverse-primary": "var(--outline-variant)",
            "on-secondary-container": "#fefcff",
            "primary-fixed-dim": "#bec6e0"
        },
        "borderRadius": {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "full": "9999px"
        },
        "spacing": {
            "unit": "0.5rem",
            "content-max": "51.25rem",
            "section-gap-md": "3rem",
            "section-gap-lg": "5rem",
            "margin-mobile": "1.25rem",
            "component-gap": "1rem",
            "gutter": "1.5rem",
            "stack-sm": "0.5rem",
            "stack-md": "1.5rem",
            "stack-lg": "3rem",
            "container-max": "87.5rem"
        },
        "fontFamily": {
            "headline-md": ["Space Grotesk"],
            "title-lg": ["Inter"],
            "headline-sm": ["Space Grotesk"],
            "body-md": ["Inter"],
            "display-lg": ["Space Grotesk"],
            "body-lg": ["Inter"],
            "label-caps": ["Space Grotesk"],
            "hint": ["Inter"],
            "display-lg-mobile": ["Space Grotesk"]
        },
        "fontSize": {
            "headline-md": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
            "title-lg": ["20px", {"lineHeight": "1.5", "fontWeight": "600"}],
            "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
            "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
            "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
            "body-lg": ["18px", {"lineHeight": "1.7", "fontWeight": "400"}],
            "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700"}],
            "hint": ["13px", {"lineHeight": "1.4", "fontWeight": "400"}],
            "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}]
        }
    }
  },
  plugins: [],
}
